using System;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Formatting;

namespace Kentico.Kontent.ModelGenerator.Core
{
    public abstract class ClassCodeGenerator
    {
        public const string DefaultNamespace = "KenticoKontentModels";

        public ClassDefinition ClassDefinition { get; }

        public string ClassFilename { get; }

        public string Namespace { get; }

        protected ClassCodeGenerator(ClassDefinition classDefinition, string classFilename, string @namespace = DefaultNamespace)
        {
            ClassDefinition = classDefinition ?? throw new ArgumentNullException(nameof(classDefinition));
            ClassFilename = string.IsNullOrWhiteSpace(classFilename) ? ClassDefinition.ClassName : classFilename;
            Namespace = string.IsNullOrWhiteSpace(@namespace) ? DefaultNamespace : @namespace;
        }

        public bool OverwriteExisting => GetType() != typeof(PartialClassCodeGenerator);

        public string GenerateCode()
        {
            var usings = GetApiUsings();
            var classDeclaration = GetClassDeclaration();

            var compilationUnit = GetCompilationUnit(classDeclaration, usings);

            var customWorkspace = new AdhocWorkspace();
            return Formatter.Format(compilationUnit, customWorkspace).ToFullString().NormalizeLineEndings();
        }

        protected abstract UsingDirectiveSyntax[] GetApiUsings();

        protected virtual ClassDeclarationSyntax GetClassDeclaration() => SyntaxFactory.ClassDeclaration(ClassDefinition.ClassName)
            .AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword))
            .AddModifiers(SyntaxFactory.Token(SyntaxKind.PartialKeyword));

        protected virtual CompilationUnitSyntax GetCompilationUnit(ClassDeclarationSyntax classDeclaration, UsingDirectiveSyntax[] usings)
        {
            var compilationUnit = SyntaxFactory.CompilationUnit()
                .AddUsings(usings)
                .AddMembers(
                    SyntaxFactory.NamespaceDeclaration(SyntaxFactory.IdentifierName(Namespace))
                        .AddMembers(classDeclaration));

            compilationUnit = compilationUnit.WithLeadingTrivia(ClassDescription);

            return compilationUnit;
        }

        protected static AccessorDeclarationSyntax GetAccessorDeclaration(SyntaxKind kind) =>
            SyntaxFactory.AccessorDeclaration(kind).WithSemicolonToken(SyntaxFactory.Token(SyntaxKind.SemicolonToken));

        private static SyntaxTrivia ClassDescription => SyntaxFactory.Comment(
            @"// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class." + Environment.NewLine + Environment.NewLine);
    }
}
