using System;
using Kontent.Ai.ModelGenerator.Core.Common;
using Kontent.Ai.ModelGenerator.Core.Helpers;
using Xunit;

namespace Kontent.Ai.ModelGenerator.Tests.Helpers;

public class TextHelpersTests
{
    [Fact]
    public void GetValidPascalCaseIdentifierName_ThrowsAnExceptionForNullValue()
    {
        Assert.Throws<ArgumentNullException>(() => TextHelpers.GetValidPascalCaseIdentifierName(null));
    }

    [Theory]
    [InlineData("")]
    [InlineData("  ")]
    [InlineData("-")]
    [InlineData("$^123")]
    public void GetValidPascalCaseIdentifierName_ThrowsAnExceptionForInvalidInput(string name)
    {
        Assert.Throws<InvalidIdentifierException>(() => TextHelpers.GetValidPascalCaseIdentifierName(name));
    }

    [Theory]
    [InlineData("Simple name", "SimpleName")]
    [InlineData("Name with special chars & multiple    spaces.", "NameWithSpecialCharsMultipleSpaces")]
    [InlineData("EVERYTHING_IS_ -UPPERCASE", "EverythingIsUppercase")]
    [InlineData("date___time_field", "DateTimeField")]
    [InlineData("Multiline\r\nstring", "MultilineString")]
    [InlineData(" 1 2 3 Starts with space and numbers", "StartsWithSpaceAndNumbers")]
    [InlineData("ends with numbers 1 2 3", "EndsWithNumbers123")]
    public void GetValidPascalCaseIdentifierName(string name, string expected)
    {
        string result = TextHelpers.GetValidPascalCaseIdentifierName(name);
        Assert.Equal(expected, result);
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData(" ")]
    public void GenerateCommentString_CustomCommentIsNullOrEmptyOrWhiteSpace_Throws(string customComment)
    {
        Assert.Throws<ArgumentNullException>(() => TextHelpers.GenerateCommentString(customComment));
    }

    [Fact]
    public void GenerateCommentString_Returns()
    {
        var customComment = "// custom comment";

        var expectedComment =
            @$"// <auto-generated>
// This code was generated by a kontent-generators-net tool
// (see https://github.com/kontent-ai/model-generator-net).
//
// custom comment
// </auto-generated>{Environment.NewLine}{Environment.NewLine}";

        var result = TextHelpers.GenerateCommentString(customComment);

        Assert.Equal(expectedComment, result);

    }
}
